# References
# https://github.com/serverless/examples/blob/v3/aws-python-flask-dynamodb-api/serverless.yml
# https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml/
# https://github.com/jordaneremieff/serverless-mangum-examples/blob/main/fastapi-example/serverless.yml
# https://github.com/serverless/serverless/blob/main/docs/providers/aws/events/apigateway.md
# https://github.com/dougmoscrop/serverless-http/blob/master/docs/EXAMPLES.md
# https://www.serverless.com/blog/dynamodb-on-demand-serverless

service: content-warnings-backend

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  stage: prod # change while on feature branches!
  apiGateway:
    usagePlan:
      quota:
        limit: 5000
        offset: 2
        period: MONTH
      throttle:
        burstLimit: 200
        rateLimit: 100
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:DeleteItem
            - lambda:InvokeFunction
          # allows this resource to be modified on sls deploy.
          Resource:
            - arn:aws:lambda:us-east-1:*:*
            - Fn::GetAtt: [MoviesTable, Arn]
            - Fn::GetAtt: [CWTable, Arn]
            - Fn::GetAtt: [UserVerificationTable, Arn]
            - Fn::GetAtt: [UserTable, Arn]
  environment:
    MOVIES_TABLE: ${self:custom.movieTableName}
    CW_TABLE: ${self:custom.cwTableName}
    USER_VERIFICATION_TABLE: ${self:custom.userVerificationTableName}
    USER_TABLE: ${self:custom.userTableName}

# REST API (gives more functionality than HTTP API)
# to change to an HTTP API, simply replace "http" with "httpApi: '*'"
functions:
  app:
    handler: src.main.handler
    events:
      - httpApi: '*'

custom:
  pythonRequirements:
    dockerizePip: false
    pythonBin: python3
  movieTableName: 'the-movies-table-${self:provider.stage}'
  cwTableName: 'the-cw-table-${self:provider.stage}'
  userVerificationTableName: 'the-user-verification-table-${self:provider.stage}'
  userTableName: 'the-user-table-${self:provider.stage}'

package:
  exclude:
    - "*/**"
  include:
    - "src/**"
    - "images/**"

plugins:
  - serverless-python-requirements

resources:
  Resources:
    MoviesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.movieTableName}
    CWTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.cwTableName}
    UserVerificationTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.userVerificationTableName}
    UserTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.userTableName}
