from ..cw.ContentWarningNames import ContentWarningNames

# Information on each CW name
DESCRIPTION_DICT = {
    ContentWarningNames.Abandonment: "Parents abandoning children, friends abandoning each other. Anything related to a person leaving when they ought to stay.",
    ContentWarningNames.Ableism: "Themes related to able people (people with no mental or physical disabilities).",
    ContentWarningNames.Abortion: "Themes relating to premature termination of pregnancy and abortion.",
    ContentWarningNames.Abuse_Physical: "Any form of physical abuse including beating, hitting, or otherwise harming another individual.",
    ContentWarningNames.Abuse_Mental: "Any form of mental abuse including belittling, shaming, or telling someone they are worthless.",
    ContentWarningNames.Addiction: "Themes related to addiction to substances, gambling, or other situations.",
    ContentWarningNames.Adoption: "Themes relating to adopting a child or having a child in a foster home.",
    ContentWarningNames.Age_Gap_Relationships: "Any relationship where there is a significant age gap. Includes teacher-student relationships and adult-child relationships.",
    ContentWarningNames.Alcohol: "Themes relating to alcohol use or abuse.",
    ContentWarningNames.Amputation: "Themes relating to arms, legs, or other appendages being amputated.",
    ContentWarningNames.Anaphylaxis: "Themes relating to severe allergies or other causes of anaphylaxis.",
    ContentWarningNames.Animal_Cruelty: "Themes relating to any abuse of animals such as physical abuse, neglect, and animal testing or experimentation.",
    ContentWarningNames.Antisemitism: "Any anti-jewish themes.",
    ContentWarningNames.Anxiety_Disorders_Attacks: "Any situation where a character has an anxiety disorder or a situation where they have an anxiety attack.",
    ContentWarningNames.Arranged_Coerced_Marriage: "Any form of arranged marriage or marriage where one or both partners are forced into the arrangement.",
    ContentWarningNames.Asphyxiation_Strangulation: "Themes involving strangulation or asphyxiation.",
    ContentWarningNames.Assassination: "Any depiction of assassination.",
    ContentWarningNames.Assault: "Any form of assault including acid attacks, battery, or beatings.",
    ContentWarningNames.Asthma: "Themes relating to asthma and the related issues of asthma attacks.",
    ContentWarningNames.Banishment: "Themes relating to banishment from social groups or other communities.",
    ContentWarningNames.Bestiality: "Any form of bestiality.",
    ContentWarningNames.Blackmail: "Any situation where blackmail is involved to coerce an individual or group.",
    ContentWarningNames.Blood_Gore: "Themes with any form of blood and gore. This includes burns and any kind of mutilation that is graphically displayed.",
    ContentWarningNames.Boating_Accidents: "Any form of trauma related to ships or boats in accidents, particularly when related to boats sinking.",
    ContentWarningNames.Body_Modification: "Any form of modification to the human body including cybernetics and other alterations.",
    ContentWarningNames.Body_Shaming: "Any form of harassment or discrimination related to ones body. This includes both overweight and underweight individuals, individuals with prosthetics, or individuals with congenital deformities",
    ContentWarningNames.Branding: "Use of a hot iron or other manner to brand another human or animal.",
    ContentWarningNames.Building_Collapse: "Any situation where a building collapses.",
    ContentWarningNames.Bullying: "Any form of bullying including verbal abuse, physical bullying, and cyberbullying.",
    ContentWarningNames.Buried_Alive: "Any situation where an individual is buried alive.",
    ContentWarningNames.Cannibalism: "Any form of cannibalism where a species eats another of their own species.",
    ContentWarningNames.Captivity: "Any form of captivity or confinement.",
    ContentWarningNames.Catfishing: "A situation where someone uses an online persona to lure someone in.",
    ContentWarningNames.Cheating: "Any form of cheating on a partner or in a relationship.",
    ContentWarningNames.Childbirth: "Any visual depictions of childbirth.",
    ContentWarningNames.Concentration_Camps: "Themes involving concentration camps.",
    ContentWarningNames.Conscription: "Any form of compulsory enlistment.",
    ContentWarningNames.Consent_Issues: "Any situation where there is debatable consent or lack of consent in being touched or sexual action or similar situations.",
    ContentWarningNames.Cults: "Any depiction of cults.",
    ContentWarningNames.Dead_Bodies: "Any depiction of dead bodies, dismembered body parts, or vivid depictions of death.",
    ContentWarningNames.Death_Of_Animals: "Death of any animals.",
    ContentWarningNames.Death_Of_Loved_Ones: "Death of any loved ones: friends, family, relatives, or significant others.",
    ContentWarningNames.Death: "Any other depiction of death.",
    ContentWarningNames.Decapitation: "Any form of decapitation or removal of one's head.",
    ContentWarningNames.Depersonalization_Derealization: "Any situation where there is depersonalization, the feeling of observing oneself from outside one's body, or derealization, finding yourself detached from your surroundings.",
    ContentWarningNames.Depression: "Any depiction of depression or themes relating to depression.",
    ContentWarningNames.Dieting: "Themes relating to dieting and diet culture.",
    ContentWarningNames.Discrimination: "Any form of discrimination against any group.",
    ContentWarningNames.Disfigurement_Dismemberment: "Any form of disfigurement or dismemberment of an individual, particularly prevalent in torture situations.",
    ContentWarningNames.Disappearance_Of_Loved_One: "Any situation where a loved one disappears, particularly if there is a traumatic experience related to it.",
    ContentWarningNames.Disownment_Exile: "Any form of disownment, estrangement, or exile of an individual from a group of people or a family or society.",
    ContentWarningNames.Divorce: "Any themes relating to divorce and splitting of families.",
    ContentWarningNames.Doxing: "Any form of doxing including searching for private or identifying information on an individual.",
    ContentWarningNames.Drowning: "Themes involving drowning or any near-drowning situations.",
    ContentWarningNames.Drugs: "Any form of drug use in both medical and illegal situations, addiction or display of drugs.",
    ContentWarningNames.Dysphoria: "Any form of dysphoria.",
    ContentWarningNames.Electrocution: "Any relation to electrocution and electrical related incidents.",
    ContentWarningNames.Epilepsy: "Any depiction of epilepsy or epileptic seizures.",
    ContentWarningNames.Eugenics: "Any situation where manipulation of a population to have particular traits either at the large level or even at the selection of a child for 'perfection' sake.",
    ContentWarningNames.Fictitious_Disorder: "Situations where an individual fakes having a disorder for pity or other reasons.",
    ContentWarningNames.Fire_Incidents: "Any incident related to fire including bushfires and moderate to severe burns.",
    ContentWarningNames.Flogging_Flaying: "Any form of flogging or flaying.",
    ContentWarningNames.Gambling: "Any depiction of gambling.",
    ContentWarningNames.Gangs_Mafia: "Any depiction of gangs or mafia and violence related to gangs or mafia.",
    ContentWarningNames.Garroting: "Any depiction of garroting (death by strangulation).",
    ContentWarningNames.Genocide: "Any form of genocide of a species or group of individuals.",
    ContentWarningNames.Gentrification: "Any form of development of an area such that it pushes out the impoverished.",
    ContentWarningNames.Grief_And_Loss: "Any depictions of grief and loss.",
    ContentWarningNames.Gun_Violence: "Any depictions of gun violence.",
    ContentWarningNames.Hallucinations: "Any form of hallucinations.",
    ContentWarningNames.Hanging: "Any depiction of hanging.",
    ContentWarningNames.Hate_Crimes: "Any form of hate crimes against an individual or group of individuals.",
    ContentWarningNames.Hate_Groups: "Any group that is involved in discriminatory actions or which spreads hate against a group or denomination of people.",
    ContentWarningNames.Hazing: "Any form of hazing or systematic bullying of an individual as a trial to enter a group or society.",
    ContentWarningNames.Heart_Attack: "Any depiction of a heart attack.",
    ContentWarningNames.Home_Invasion: "Any form of home invasion or burglary.",
    ContentWarningNames.Homelessness: "Any depiction of homelessness.",
    ContentWarningNames.Homophobia: "Any derogatory depiction of homogenous relationships.",
    ContentWarningNames.Hospitalization: "Any depiction of hospitalization of an individual.",
    ContentWarningNames.Hostage_Situation: "Any situation where an individual or group is taken hostage.",
    ContentWarningNames.Hunting: "Any depiction of hunting.",
    ContentWarningNames.Inaccurate_Representation: "Any inaccurate representation of a group, add the specific group and situation in the description.",
    ContentWarningNames.Incest: "Any depiction or mention of incest.",
    ContentWarningNames.Indentured_Slavery: "Any depiction of indentured servitude or slavery or forced labor.",
    ContentWarningNames.Injury_Illness: "Any depiction of injury or illness.",
    ContentWarningNames.Imprisonment_Incarceration: "Any depiction of imprisonment or incarceration.",
    ContentWarningNames.Internment_Camps: "Any depiction of an internment camp.",
    ContentWarningNames.Intrusive_Thoughts: "Any situation where an individual has intrusive thoughts that are potentially detrimental.",
    ContentWarningNames.Islamophobia: "Themes including hate against Islam.",
    ContentWarningNames.Kidnapping: "Any situation where there is capture or kidnapping of an individual.",
    ContentWarningNames.KKK: "Any mention of the Ku Klux Klan or sister white- supremacist organizations.",
    ContentWarningNames.Knife_Violence: "Any form of violence involving a knife and potentially knife wounds.",
    ContentWarningNames.Labor_Camps: "Any mention of labor camps.",
    ContentWarningNames.Loss_Of_Autonomy: "Any situation where an incident or event results in the loss of autonomy of an individual.",
    ContentWarningNames.Loss_Of_Sense: "Any situation where an individual loses their senses permanently.",
    ContentWarningNames.Lynching: "Any situation where lynching is involved.",
    ContentWarningNames.Massacres_Mass_Murder: "Any depiction of massacres or mass murder events.",
    ContentWarningNames.Major_Illnesses: "Any depiction of a major illness with physical symptoms such as cancer, chronic illness, heart disease etc. Mental illnesses are a different category however.",
    ContentWarningNames.Medical_Experimentation: "Any form of medical experimentation whether it be on animals or humans or other species.",
    ContentWarningNames.Medical_Treatment_Surgery: "Any form of medical treatment or surgery, especially those with vivid imagery.",
    ContentWarningNames.Memory_Disorders: "Any form of memory disorder including amnesia, Alzheimer’s, and dementia.",
    ContentWarningNames.Mind_Control_Possession: "Any depiction of mind control or possession.",
    ContentWarningNames.Miscarriage: "Any mention or depiction of miscarriage.",
    ContentWarningNames.Misgendering: "Any mention or depiction of misgendering including deadnaming.",
    ContentWarningNames.Misogyny: "Any strong evidence of misogyny, gender role enforcement, or hate acts against women.",
    ContentWarningNames.Motorcycle_Accidents: "Any accidents relating to motorcycles.",
    ContentWarningNames.Mugging: "Any mention or depiction of mugging.",
    ContentWarningNames.Mutilation: "Any form of mutilation.",
    ContentWarningNames.Murder: "Any depiction of murder.",
    ContentWarningNames.Induced_Illness: "Any situation where someone induces or fakes illness until symptoms of the illness become part of their daily life.",
    ContentWarningNames.Natural_Disasters: "Any form of natural disaster.",
    ContentWarningNames.Necrophilia: "Any depiction of necrophilia.",
    ContentWarningNames.Needles: "Any depiction of needles.",
    ContentWarningNames.Neglect: "Any depiction of neglect.",
    ContentWarningNames.Neurological_Diseases: "Any form of mental illness or neurological disease. (Alzheimers, Bipolar, Conversion Therapy, Dissociation, OCD, Schizophrenia, Sleep Disorders).",
    ContentWarningNames.Nightmares: "Any depiction of nightmares or night terrors.",
    ContentWarningNames.Nuclear_Disaster: "Any depiction of a nuclear disaster.",
    ContentWarningNames.Organized_Crime: "Any depiction of organized crime.",
    ContentWarningNames.Overdose: "Any depiction of overdose.",
    ContentWarningNames.Pedophilia: "Any depiction or mention of pedophilia, including adult- minor relationships and any evidence of pedophilic actions. Lolicon (cartoon depictions of adult-minor relationships) is also regarded as pedophilia on this site.",
    ContentWarningNames.Pandemic_Plague: "Any depiction of a pandemic or plague.",
    ContentWarningNames.Panic_Attacks: "Any depiction of panic attacks.",
    ContentWarningNames.Paralysis: "Any situation resulting in paralysis or depiction of paralysis.",
    ContentWarningNames.Paraplegia: "Any depiction of paraplegia.",
    ContentWarningNames.Phobias: "Any mention or depiction of phobias, particularly those including vivid imagery.",
    ContentWarningNames.Plane_Crash: "Any situation revolving around a plane crash.",
    ContentWarningNames.Poisoning: "Any depiction of poisoning.",
    ContentWarningNames.Police_Brutality: "Any depiction of police brutality.",
    ContentWarningNames.PTSD: "Any depiction or vivid imagery related to PTSD.",
    ContentWarningNames.Pornography: "Any depiction or mention of pornography.",
    ContentWarningNames.Poverty: "Any depiction of poverty or situation involving poverty.",
    ContentWarningNames.Pregnancy: "Any depiction of pregnancy.",
    ContentWarningNames.Pregnancy_Involuntary: "Any depiction of involuntary pregnancy that negatively affects any party involved.",
    ContentWarningNames.Prudism: "Any situation where the choice to be promiscuous or display one's body in a promiscuous way is shown in a negative light or shamed.",
    ContentWarningNames.Psychiatric_Hospitalization: "Any depiction of hospitalization in a psychiatric ward.",
    ContentWarningNames.Racism: "Any depiction or mention of racism.",
    ContentWarningNames.Rape_Sexual_Abuse: "Any depiction of rape or sexual abuse, particularly if vivid imagery is involved.",
    ContentWarningNames.Refugee_Experiences: "Any depiction of refugees, particularly vivid imagery of the strife and struggle involved.",
    ContentWarningNames.Regicide: "Any depiction of regicide or the murder of a country’s rulers.",
    ContentWarningNames.Religious_Persecution: "Any form of religious persecution for any religion.",
    ContentWarningNames.Riots: "Any depiction of riots.",
    ContentWarningNames.Scalping: "Any depiction of scalping.",
    ContentWarningNames.Scars: "Any vivid imagery of scars.",
    ContentWarningNames.School_Shooting: "Any vivid imagery or depiction of school shootings.",
    ContentWarningNames.Seizures: "Any depiction of seizures.",
    ContentWarningNames.Self_Harm: "Any depiction or mention of self-harm.",
    ContentWarningNames.Self_Immolation: "Any depiction of self-immolation (setting oneself on fire).",
    ContentWarningNames.Sensory_Deprivation: "Any depiction of non-permanent or induced sensory deprivation.",
    ContentWarningNames.Sex_Addiction: "Any depiction or mention of sex addiction.",
    ContentWarningNames.Sexism: "Any depiction or situation where sexism is displayed.",
    ContentWarningNames.Sexual_Abuse_Assault_Harassment: "Any form of sexual abuse, assault, or harassment.",
    ContentWarningNames.Sex_Trafficking: "Any form of sex trafficking.",
    ContentWarningNames.Sex_Worker_Shaming: "Any situation where there is sex-worker shaming.",
    ContentWarningNames.Stalking: "Any depiction of or situation where stalking is involved.",
    ContentWarningNames.Starvation_Dehydration: "Any depiction of starvation or dehydration.",
    ContentWarningNames.Sterilization: "Any depiction or mention of sterilization, particularly if it is a forced or non-consensual situation.",
    ContentWarningNames.Stillbirth: "Any depiction or mention of stillbirth.",
    ContentWarningNames.Strangulation: "Any depiction or mention of strangulation or suffocation.",
    ContentWarningNames.Stroke: "Any depiction or mention of stroke.",
    ContentWarningNames.Suicide: "Any depiction or vivid imagery related to suicide.",
    ContentWarningNames.Teen_Child_Pregnancy: "Any depiction or mention of teen or child pregnancy, particularly if forced or non-consensual.",
    ContentWarningNames.Terminal_Illness: "Any depiction or mention of terminal illness.",
    ContentWarningNames.Terrorism: "Any situation where terrorism is depicted or implied.",
    ContentWarningNames.Torture: "Any situation where torture is depicted.",
    ContentWarningNames.Train_Accidents: "Any accident relating to trains, including derailing and death by train.",
    ContentWarningNames.Transphobia: "Any depiction of transphobia, including deadnaming, misgendering, or harmful stereotyping.",
    ContentWarningNames.Victim_Blaming: "Any depiction of victim blaming, particularly in situations such as rape.",
    ContentWarningNames.Vomiting: "Any depiction of vomiting.",
    ContentWarningNames.War_Incidents: "Any incidents relating to war including gassing, explosions, and military violence.",
    ContentWarningNames.Weight_Disorders: "Any mention of or situation related to weight disorders such as anorexia and bulimia as well as food shaming or fat shaming.",
    ContentWarningNames.Weight_Loss_Gain: "Any mention of weight loss or gain.",
    ContentWarningNames.Witchcraft: "Any mention of witchcraft or persecution for witchcraft.",
    ContentWarningNames.Whipping: "Any depiction of whipping, particularly vivid imagery related to whipping.",
    ContentWarningNames.White_Supremacy: "Any depiction or mention of white supremacy, particularly when used in discriminatory ways.",
    ContentWarningNames.Workplace_Harassment: "Any depiction or mention of workplace harassment.",
    ContentWarningNames.None_Type: "No description.",
    ContentWarningNames.Deportation_Displacement: "Any depiction of deportation or displacement from an established home.",
    ContentWarningNames.Sex_Work_Slavery: "Any depiction of sex work or sex slavery.",
}
