name: Security Scan

on:
  push:
    paths:
      - 'src/**'

jobs:
  lint:
    runs-on: self-hosted
    steps:
      - uses: ShiftLeftSecurity/scan-action@master
        with:
            type: "credscan,java,depscan"
