name: Security Scan

on:
  push:
    paths:
      - 'src/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: ShiftLeftSecurity/scan-action@master
        with:
            type: "credscan,python,depscan"
