# References
# https://github.com/serverless/github-action
# https://dev.to/jakewitcher/using-env-files-for-environment-variables-in-python-applications-55a1
# https://www.thisdot.co/blog/github-actions-for-serverless-framework-deployments
#
# as per Apache 2.0 License, we have put in comments any changes to codefile

# changed to 'main' from 'master'
name: Deploy main branch

# modified 'on' conditions to reference new branch name ('main') and to filter on which
# codefiles have been modified
on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'serverless.yaml'
      - 'requirements.txt'

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install  # changed to 'install' from 'ci'
    - name: create .env file # added this step to create a .env file
      run: |
        touch .env
        echo TMDB_API_KEY=${{ secrets.TMDB_API_KEY }} >> .env
        echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env
        echo JWT_ALGORITHM=${{ secrets.JWT_ALGORITHM }} >> .env
        echo JWT_SUDO_LIFETIME=${{ secrets.JWT_SUDO_LIFETIME }} >> .env
        echo JWT_USER_LIFETIME=${{ secrets.JWT_USER_LIFETIME }} >> .env
        echo SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY }} >> .env
    - name: serverless deploy
      uses: serverless/github-action@v3.1
      with:
        args: deploy
      env:
        # removed line detailing serverless access key and uncommented secret keys
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
